version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    image: diemdt9403/plantstore:v1.1
    container_name: springboot-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
    env_file:
      - .env
networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
